//
//  AudioKit iOS.h
//  AudioKit iOS
//
//  Created by Pawel Kania on 01/10/2016.
//  Copyright © 2016 AudioKit. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for AudioKit iOS.
FOUNDATION_EXPORT double AudioKit_iOSVersionNumber;

//! Project version string for AudioKit iOS.
FOUNDATION_EXPORT const unsigned char AudioKit_iOSVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <AudioKit_iOS/PublicHeader.h>

#import <AudioKit_iOS/AKCompatibility.h>
#import <AudioKit_iOS/AKFoundation.h>
#import <AudioKit_iOS/AKManager.h>
#import <AudioKit_iOS/AKOrchestra.h>
#import <AudioKit_iOS/AKSettings.h>
#import <AudioKit_iOS/AKMidi.h>
#import <AudioKit_iOS/AKMidiEvent.h>
#import <AudioKit_iOS/AKMidiInstrument.h>
#import <AudioKit_iOS/AKMidiNote.h>
#import <AudioKit_iOS/AKInstrument.h>
#import <AudioKit_iOS/AKInstrumentProperty.h>
#import <AudioKit_iOS/AKNote.h>
#import <AudioKit_iOS/AKNoteProperty.h>
#import <AudioKit_iOS/AKParameter+Operation.h>
#import <AudioKit_iOS/AKTrackedAmplitude.h>
#import <AudioKit_iOS/AKTrackedAmplitudeFromFSignal.h>
#import <AudioKit_iOS/AKTrackedFrequency.h>
#import <AudioKit_iOS/AKTrackedFrequencyFromFSignal.h>
#import <AudioKit_iOS/AKCrossSynthesizedFFT.h>
#import <AudioKit_iOS/AKFFT.h>
#import <AudioKit_iOS/AKFFTProcessor.h>
#import <AudioKit_iOS/AKFFTTableReader.h>
#import <AudioKit_iOS/AKFFTTableWriter.h>
#import <AudioKit_iOS/AKFilteredFFT.h>
#import <AudioKit_iOS/AKMaskedFFT.h>
#import <AudioKit_iOS/AKMixedFFT.h>
#import <AudioKit_iOS/AKPhaseLockedVocoder.h>
#import <AudioKit_iOS/AKResynthesizedAudio.h>
#import <AudioKit_iOS/AKScaledFFT.h>
#import <AudioKit_iOS/AKSpectralVocoder.h>
#import <AudioKit_iOS/AKWarpedFFT.h>
#import <AudioKit_iOS/AKAdditiveCosines.h>
#import <AudioKit_iOS/AKAssignment.h>
#import <AudioKit_iOS/AKDifference.h>
#import <AudioKit_iOS/AKInverse.h>
#import <AudioKit_iOS/AKMaximum.h>
#import <AudioKit_iOS/AKMinimum.h>
#import <AudioKit_iOS/AKMultipleInputMathOperation.h>
#import <AudioKit_iOS/AKProduct.h>
#import <AudioKit_iOS/AKSingleInputMathOperation.h>
#import <AudioKit_iOS/AKSum.h>
#import <AudioKit_iOS/AKTableValue.h>
#import <AudioKit_iOS/AKADSREnvelope.h>
#import <AudioKit_iOS/AKLine.h>
#import <AudioKit_iOS/AKLinearADSREnvelope.h>
#import <AudioKit_iOS/AKLinearEnvelope.h>
#import <AudioKit_iOS/AKGranularSynthesisTexture.h>
#import <AudioKit_iOS/AKGranularSynthesizer.h>
#import <AudioKit_iOS/AKSinusoidBursts.h>
#import <AudioKit_iOS/AKMonoSoundFileLooper.h>
#import <AudioKit_iOS/AKStereoSoundFileLooper.h>
#import <AudioKit_iOS/AKTableLooper.h>
#import <AudioKit_iOS/AKPortamento.h>
#import <AudioKit_iOS/AKVibrato.h>
#import <AudioKit_iOS/AKFMOscillator.h>
#import <AudioKit_iOS/AKLowFrequencyOscillator.h>
#import <AudioKit_iOS/AKOscillator.h>
#import <AudioKit_iOS/AKPhasor.h>
#import <AudioKit_iOS/AKVCOscillator.h>
#import <AudioKit_iOS/AKMandolin.h>
#import <AudioKit_iOS/AKMarimba.h>
#import <AudioKit_iOS/AKPluckedString.h>
#import <AudioKit_iOS/AKStruckMetalBar.h>
#import <AudioKit_iOS/AKVibes.h>
#import <AudioKit_iOS/AKBambooSticks.h>
#import <AudioKit_iOS/AKCabasa.h>
#import <AudioKit_iOS/AKCrunch.h>
#import <AudioKit_iOS/AKDroplet.h>
#import <AudioKit_iOS/AKGuiro.h>
#import <AudioKit_iOS/AKSandPaper.h>
#import <AudioKit_iOS/AKSekere.h>
#import <AudioKit_iOS/AKSleighbells.h>
#import <AudioKit_iOS/AKStick.h>
#import <AudioKit_iOS/AKTambourine.h>
#import <AudioKit_iOS/AKBeatenPlate.h>
#import <AudioKit_iOS/AKBowedString.h>
#import <AudioKit_iOS/AKFlute.h>
#import <AudioKit_iOS/AKSimpleWaveGuideModel.h>
#import <AudioKit_iOS/AKInterpolatedRandomNumberPulse.h>
#import <AudioKit_iOS/AKJitter.h>
#import <AudioKit_iOS/AKNoise.h>
#import <AudioKit_iOS/AKRandomNumbers.h>
#import <AudioKit_iOS/AKSegmentArray.h>
#import <AudioKit_iOS/AKSegmentArrayLoop.h>
#import <AudioKit_iOS/AKAudioInput.h>
#import <AudioKit_iOS/AKAudioOutput.h>
#import <AudioKit_iOS/AKFileInput.h>
#import <AudioKit_iOS/AKLog.h>
#import <AudioKit_iOS/AKMidiInput.h>
#import <AudioKit_iOS/AKMonoFileInput.h>
#import <AudioKit_iOS/AKMP3FileInput.h>
#import <AudioKit_iOS/AKParameterChangeLog.h>
#import <AudioKit_iOS/AKConvolution.h>
#import <AudioKit_iOS/AKStereoConvolution.h>
#import <AudioKit_iOS/AKDelay.h>
#import <AudioKit_iOS/AKMultitapDelay.h>
#import <AudioKit_iOS/AKVariableDelay.h>
#import <AudioKit_iOS/AKCompressor.h>
#import <AudioKit_iOS/AKCompressorExpander.h>
#import <AudioKit_iOS/AKDistortion.h>
#import <AudioKit_iOS/AKDopplerEffect.h>
#import <AudioKit_iOS/AKFlanger.h>
#import <AudioKit_iOS/AKPitchShifter.h>
#import <AudioKit_iOS/AKRingModulator.h>
#import <AudioKit_iOS/AKAntiresonantFilter.h>
#import <AudioKit_iOS/AKClipper.h>
#import <AudioKit_iOS/AKCombFilter.h>
#import <AudioKit_iOS/AKDCBlock.h>
#import <AudioKit_iOS/AKDecimator.h>
#import <AudioKit_iOS/AKDeclick.h>
#import <AudioKit_iOS/AKEqualizerFilter.h>
#import <AudioKit_iOS/AKHighPassFilter.h>
#import <AudioKit_iOS/AKHilbertTransformer.h>
#import <AudioKit_iOS/AKLowPassFilter.h>
#import <AudioKit_iOS/AKMoogLadder.h>
#import <AudioKit_iOS/AKMoogVCF.h>
#import <AudioKit_iOS/AKResonantFilter.h>
#import <AudioKit_iOS/AKStringResonator.h>
#import <AudioKit_iOS/AKThreePoleLowpassFilter.h>
#import <AudioKit_iOS/AKVariableFrequencyResponseBandPassFilter.h>
#import <AudioKit_iOS/AKBandPassButterworthFilter.h>
#import <AudioKit_iOS/AKBandRejectButterworthFilter.h>
#import <AudioKit_iOS/AKHighPassButterworthFilter.h>
#import <AudioKit_iOS/AKLowPassButterworthFilter.h>
#import <AudioKit_iOS/AKHighShelfParametricEqualizerFilter.h>
#import <AudioKit_iOS/AKLowShelfParametricEqualizerFilter.h>
#import <AudioKit_iOS/AKPeakingParametricEqualizerFilter.h>
#import <AudioKit_iOS/AKBallWithinTheBoxReverb.h>
#import <AudioKit_iOS/AKFlatFrequencyResponseReverb.h>
#import <AudioKit_iOS/AKParallelCombLowPassFilterReverb.h>
#import <AudioKit_iOS/AKReverb.h>
#import <AudioKit_iOS/AK3DBinauralAudio.h>
#import <AudioKit_iOS/AKBalance.h>
#import <AudioKit_iOS/AKMix.h>
#import <AudioKit_iOS/AKPanner.h>
#import <AudioKit_iOS/AKAudio.h>
#import <AudioKit_iOS/AKConstant.h>
#import <AudioKit_iOS/AKControl.h>
#import <AudioKit_iOS/AKFSignal.h>
#import <AudioKit_iOS/AKParameter.h>
#import <AudioKit_iOS/AKStereoAudio.h>
#import <AudioKit_iOS/AKEvent.h>
#import <AudioKit_iOS/AKPhrase.h>
#import <AudioKit_iOS/AKSequence.h>
#import <AudioKit_iOS/AKSoundFont.h>
#import <AudioKit_iOS/AKSoundFontInstrument.h>
#import <AudioKit_iOS/AKSoundFontInstrumentPlayer.h>
#import <AudioKit_iOS/AKSoundFontPreset.h>
#import <AudioKit_iOS/AKSoundFontPresetPlayer.h>
#import <AudioKit_iOS/AKSoundFileTable.h>
#import <AudioKit_iOS/AKTable.h>
#import <AudioKit_iOS/AKExponentialTableGenerator.h>
#import <AudioKit_iOS/AKFourierSeriesTableGenerator.h>
#import <AudioKit_iOS/AKHarmonicCosineTableGenerator.h>
#import <AudioKit_iOS/AKLineTableGenerator.h>
#import <AudioKit_iOS/AKRandomDistributionTableGenerator.h>
#import <AudioKit_iOS/AKTableGenerator.h>
#import <AudioKit_iOS/AKWindowTableGenerator.h>
#import <AudioKit_iOS/AKSampler.h>
#import <AudioKit_iOS/AKTools.h>
#import <AudioKit_iOS/AKAmplifier.h>
#import <AudioKit_iOS/AKStereoAmplifier.h>
#import <AudioKit_iOS/AKAudioAnalyzer.h>
#import <AudioKit_iOS/AKBambooSticksInstrument.h>
#import <AudioKit_iOS/AKMandolinInstrument.h>
#import <AudioKit_iOS/AKMarimbaInstrument.h>
#import <AudioKit_iOS/AKPluckedStringInstrument.h>
#import <AudioKit_iOS/AKSekereInstrument.h>
#import <AudioKit_iOS/AKSleighbellsInstrument.h>
#import <AudioKit_iOS/AKStickInstrument.h>
#import <AudioKit_iOS/AKStruckMetalBarInstrument.h>
#import <AudioKit_iOS/AKTambourineInstrument.h>
#import <AudioKit_iOS/AKVibraphoneInstrument.h>
#import <AudioKit_iOS/AKAudioFilePlayer.h>
#import <AudioKit_iOS/AKStereoAudioFilePlayer.h>
#import <AudioKit_iOS/AKMicrophone.h>
#import <AudioKit_iOS/AKDelayPedal.h>
#import <AudioKit_iOS/AKPitchShifterPedal.h>
#import <AudioKit_iOS/AKReverbPedal.h>
#import <AudioKit_iOS/AKFMOscillatorInstrument.h>
#import <AudioKit_iOS/AKVCOscillatorInstrument.h>
#import <AudioKit_iOS/AKBeatClock.h>
#import <AudioKit_iOS/AKAudioFFTPlot.h>
#import <AudioKit_iOS/AKAudioInputFFTPlot.h>
#import <AudioKit_iOS/AKAudioInputPlot.h>
#import <AudioKit_iOS/AKAudioInputRollingWaveformPlot.h>
#import <AudioKit_iOS/AKAudioOutputFFTPlot.h>
#import <AudioKit_iOS/AKAudioOutputPlot.h>
#import <AudioKit_iOS/AKAudioOutputRollingWaveformPlot.h>
#import <AudioKit_iOS/AKAudioPlot.h>
#import <AudioKit_iOS/AKAudioRollingWaveformPlot.h>
#import <AudioKit_iOS/AKFloatPlot.h>
#import <AudioKit_iOS/AKInstrumentPropertyPlot.h>
#import <AudioKit_iOS/AKPlotView.h>
#import <AudioKit_iOS/AKStereoOutputPlot.h>
#import <AudioKit_iOS/AKTablePlot.h>
#import <AudioKit_iOS/EZAudio.h>
#import <AudioKit_iOS/EZAudioDisplayLink.h>
#import <AudioKit_iOS/EZAudioFFT.h>
#import <AudioKit_iOS/EZAudioFloatConverter.h>
#import <AudioKit_iOS/EZAudioFloatData.h>
#import <AudioKit_iOS/EZAudioPlot.h>
#import <AudioKit_iOS/EZAudioUtilities.h>
#import <AudioKit_iOS/EZPlot.h>
#import <AudioKit_iOS/TPCircularBuffer.h>
#import <AudioKit_iOS/AKLevelMeter.h>
#import <AudioKit_iOS/AKPropertyLabel.h>
#import <AudioKit_iOS/AKPropertySlider.h>
#import <AudioKit_iOS/CsoundObj.h>
